### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by wangkaihong** [hcatic/CS506#1]
Hi,

The project’s overall design is strong, and the proposal is thorough and well-structured. However, I’m unclear about the primary focus: are we aiming to calculate ROI or predict rental income? The project would already be meaningful if it concentrated solely on predicting rental income based on listing features. Including a recommendation system might be overly ambitious. In practice, ROI is likely to be closely tied to rental income, making the additional recommendation layer seem unnecessary, as users can simply choose the one with the highest rental income (or simply minus the cost of the property).

**Comment by hcatic** [comment]
Ok. We will aim to predict rental income based on listing features.
